/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package democuestionario;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Jorge
 */
public class CuestionarioForm extends javax.swing.JFrame {
    private String respuesta = "El avestruz";
    private FlowLayout layout;
    /**
     * Creates new form CuestionarioForm
     */
    public CuestionarioForm() {
        initComponents();
        layout = new FlowLayout(FlowLayout.CENTER,5,5);
        setLayout(layout);
        
        //add(labelPregunta);
        
        radioOpc1.setSelected(false);
        radioOpc2.setSelected(false);
        radioOpc3.setSelected(false);
        radioOpc4.setSelected(false);
        
        add(panelPreguntas);
        
        ButtonHandler handler = new ButtonHandler();
        botonRespuesta.addActionListener(handler);
        
    }
    private class ButtonHandler implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            //seleccion de respuesta
            for (Enumeration<AbstractButton> buttons = buttonGroup1.getElements(); buttons.hasMoreElements();) {
                AbstractButton button = buttons.nextElement();

                if (button.isSelected()) {
                    //System.out.println(button.getText());
                    if(respuesta == button.getText()){
                        JOptionPane.showMessageDialog(null,"FELICITACIONES RESPUESTA CORRECTA!","Respuesta correcta",JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        JOptionPane.showMessageDialog(null,"RESPUESTA INCORRECTA INTENTA DE NUEVO","Respuesta incorrecta",JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelPreguntas = new javax.swing.JPanel();
        radioOpc1 = new javax.swing.JRadioButton();
        radioOpc2 = new javax.swing.JRadioButton();
        radioOpc3 = new javax.swing.JRadioButton();
        radioOpc4 = new javax.swing.JRadioButton();
        labelPregunta = new javax.swing.JLabel();
        botonRespuesta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trivia");

        buttonGroup1.add(radioOpc1);
        radioOpc1.setText("El ganso");

        buttonGroup1.add(radioOpc2);
        radioOpc2.setText("La gallina");

        buttonGroup1.add(radioOpc3);
        radioOpc3.setText("El avestruz");

        buttonGroup1.add(radioOpc4);
        radioOpc4.setText("La codorniz");

        labelPregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPregunta.setText("¿Cual fue la primera ave domesticada?");

        botonRespuesta.setText("Responder");

        javax.swing.GroupLayout panelPreguntasLayout = new javax.swing.GroupLayout(panelPreguntas);
        panelPreguntas.setLayout(panelPreguntasLayout);
        panelPreguntasLayout.setHorizontalGroup(
            panelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreguntasLayout.createSequentialGroup()
                .addGroup(panelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPreguntasLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(labelPregunta))
                    .addGroup(panelPreguntasLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(panelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioOpc4)
                            .addComponent(radioOpc2)
                            .addComponent(radioOpc1)
                            .addComponent(radioOpc3)
                            .addComponent(botonRespuesta))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        panelPreguntasLayout.setVerticalGroup(
            panelPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPreguntasLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(labelPregunta)
                .addGap(54, 54, 54)
                .addComponent(radioOpc1)
                .addGap(18, 18, 18)
                .addComponent(radioOpc2)
                .addGap(18, 18, 18)
                .addComponent(radioOpc3)
                .addGap(18, 18, 18)
                .addComponent(radioOpc4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(botonRespuesta)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPreguntas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPreguntas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuestionarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuestionarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuestionarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuestionarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CuestionarioForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRespuesta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel labelPregunta;
    private javax.swing.JPanel panelPreguntas;
    private javax.swing.JRadioButton radioOpc1;
    private javax.swing.JRadioButton radioOpc2;
    private javax.swing.JRadioButton radioOpc3;
    private javax.swing.JRadioButton radioOpc4;
    // End of variables declaration//GEN-END:variables
}
